### PR TITLE
Feature/add testing badges

### PR DESCRIPTION
**Pull request by aninternetof**
Adds travis testing badge.
Sets up coveralls to provide us with a badge for coverage (https://coveralls.io/github/aninternetof/rovercode-web). I tested the coverage badge for this branch, but the badge for development will be unknown until we pull something into development.

### CODE REVIEW

**Comment by aninternetof** [comment]
@cabarnes , any idea why this is still blocked? I'm reading about "status checks".

**Comment by cabarnes** [comment]
No, I was trying to figure that out last night. Everything shows as passed. Not sure if it's related to `coveralls` since that was added recently?

**Comment by aninternetof** [comment]
That was my thought. I'll see is any further enabling I need to do in the admin settings tab.

**Comment by aninternetof** [comment]
So I've disabled status checks requirements completely, and it's still saying this. Maybe this pull request instance is just hosed. I'm going to re-enable the checks, then create a new pull request.

Maybe it was challenging for github to handle a pull request that added something (coveralls) that affects the operation of a pull request!

**Pull request closed without merging**
